/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medicalstore;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class SearchMedicine extends javax.swing.JInternalFrame {

	JPanel p;
	JScrollPane sc;
	Connection con;
	Statement st;
	ResultSetMetaData rm;
	ResultSet rs;
	String column[];
	DefaultTableModel dm;
	int col,count;
        boolean flag=true,flag1=true;
        String query=null;
    /**
     * Creates new form BillReport1
     */
    public SearchMedicine() {
        setVisible(true);
        
        initComponents();
        dm=new DefaultTableModel();
        tb.setEnabled(false);
        
        try{
            Class.forName("org.apache.derby.jdbc.ClientDriver");
		con=DriverManager.getConnection("jdbc:derby://localhost:1527/MedicalStore","aa","123");
		st=con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,
                ResultSet.CONCUR_UPDATABLE);
        }
        catch(Exception e)
        {
            System.out.println("Connection not setup");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(975, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Medicine Name :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 38, 97, -1));
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 35, 158, -1));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 73, -1, -1));

        jButton2.setText("Show All Data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 73, -1, -1));

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Company_Name", "Medicine_Name", "Product_Exp", "Product_Price", "Product_Qty", "Total"
            }
        ));
        tb.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tb);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 102, 740, 260));

        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 73, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         flag1=false;
         while(dm.getRowCount()>0)
        {
            for(int i=0;i<dm.getRowCount();i++)
            {
                dm.removeRow(i);
                
            }
            
        }
         jButton2.disable();
        
        try
		{
                
		
		rs=st.executeQuery("select * from inventory");
                if(flag==true)
                { flag=false;
		rm=rs.getMetaData();
		col=rm.getColumnCount();
		column=new String[col];
                
                
		for(count=0;count<column.length;count++)
		{
		column[count]=rm.getColumnName(count+1);
		dm.addColumn(column[count]);
               
                }
                
		
                }
		while(rs.next())
		{
			
		dm.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)});
                }
                
		tb.setModel(dm);
		
		
		}
		catch(Exception e)
		{
		System.out.println("Error in connectivity"+e);
		}
	        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       

        flag1=false;
        while(dm.getRowCount()>0)
        {
            for(int i=0;i<dm.getRowCount();i++)
            {
                dm.removeRow(i);
                
            }
            
        }
        jButton2.enable();
        
        
        
        try
		{
                 
                     String name=txtname.getText().trim();
        
                     query="select * from inventory where product_name like '%"+name+"%'";
                     
                 if(txtname.getText().isEmpty()==true)
                 {
                     JOptionPane.showMessageDialog(null,"Enter Medicine Name ");
                
                 }
                 
                 rs=st.executeQuery(query);
		
                if(flag==true)
                {flag=false;
		rm=rs.getMetaData();
		col=rm.getColumnCount();
		column=new String[col];
		for(count=0;count<column.length;count++)
		{
		column[count]=rm.getColumnName(count+1);
                
       		dm.addColumn(column[count]);
                
                }
		}
		while(rs.next())
		{
			
		dm.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)});
                }
                
		tb.setModel(dm);
                 
	
		}
		catch(Exception e)
		{
		System.out.println("Error in connectivity"+e);
		}
        txtname.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            
        if(flag1==false)
        {
        try {
                
                st.close();
                rs.close();
                
            } catch (SQLException ex) {
                Logger.getLogger(SearchMedicine.class.getName()).log(Level.SEVERE, null, ex);
            }
                    
        this.dispose();  
        }
        else 
         this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
